var movies = [
    {
        "id": 1,
        "title": "Wonka",
        "image": "https://catalog.cinema-api.com/cf/images/ncg-images/e25e4aaca2984ed6be4c14b10f63f9e2.jpg?width=240&version=9488B36E1CFD30F459DD877D56E6975B&format=webp",
        "date": "13 dec 2023",
        "genre": "Familj, Äventyr, Komedi",
        "description": "Berättelsen om en ung Willy Wonka och hans äventyr innan han öppnade världens mest kända chokladfabrik.",
    },
    {
        "id": 2,
        "title": "The Hunger Games: The Ballad of Songbirds and Snakes",
        "image": "https://catalog.cinema-api.com/cf/images/ncg-images/ba7530a7f8124ae7af340d526fe8cdb8.jpg?width=240&version=E734CF5BD980C24E1752431597AA3C4C&format=webp",
        "date": "17 nov 2023",
        "genre": "Äventyr,Fantasy,Drama",
        "description": "Vi får följa Coriolanus Snow vid 18 års ålder, flera år innan han skulle bli Panems tyranniska president. Coriolanus är stilig och charmig, och även om det är svåra tider för Snow-familjen, ser han en chans till en förändring när han väljs till mentor för de 10:e hungerspelen. Snabbt krossas hans glädje när han får i uppdrag att vara mentor för en flicka från fattiga distrikt 12.", 
    },
    {
        "id": 3,
        "title": "Knuckertz & snutjakten",
        "image": "https://catalog.cinema-api.com/cf/images/ncg-images/82fd232bf26a4e36b897a56dec4fcda8.jpg?width=240&version=384CE26DACA224CDDBD7FF7072029E3E&format=webp",
        "date": "1 dec 2023",
        "genre": "Familj",
        "description": "Hunden Snuten är Tures bästa vän. Men det verkar som familjen Knyckertz snott den. Ture måste välja, ska han vara ärlig och lämna tillbaka hunden, eller behålla den och därmed hjälpa familjen att genomföra en livsfarlig kupp? Sanningen är inte alltid den man tror och Tures beslut kommer leda till en större katastrof än han kunnat Knyckertz & snutjakten tar den älskade tjuvfamiljen från böckerna och julkalendern till landets biografer i ett spännande äventyr för hela familjen.", 
    },
    {
        "id": 4,
        "title": "Önskan",
        "image": "https://catalog.cinema-api.com/cf/images/ncg-images/d0df07c700694890815a5a07a7c95c92.jpg?width=240&version=6035CB661C964431501A7FE6777F7055&format=webp",
        "date": "8 dec 2023",
        "genre": "Animerat,Äventyr,Komedi,Familj",
        "description": "Vi får följa med till det magiska kungariket Rosas, där Asha, en skarpsinnig idealist, gör en önskan så stor att den besvaras av en kosmisk kraft - en liten boll av gränslös energi vid namn Star. Tillsammans konfronterar Asha och Star en ytterst formidabel fiende - härskaren över Rosas, kung Magnifico - för att rädda hennes folk och bevisa att när en modig människas vilja slår ihop med stjärnornas magi, kan underbara saker hända.", 
    },
    {
        "id": 5,
        "title": "Napoleon",
        "image": "https://catalog.cinema-api.com/cf/images/ncg-images/e4b092edb39e41ae8a54b7a2f87c08a0.jpg?width=240&version=D4FE1F1C62AECE2B7E0E22D2AB13E53A&format=webp",
        "date": "22 nov 2023",
        "genre": "Action,Biografi,Drama",
        "description": "Vi får följa den franska kejsaren Napoleon Bonapartes snabba, hänsynslösa klättring till makten genom hans komplicerade förhållande till sin stora kärlek, Josephine.", 
    },
    {
        "id": 6,
        "title": "Pojken och hägern",
        "image": "https://catalog.cinema-api.com/cf/images/ncg-images/c206c4b4332c4f1abfe5dab233694eba.jpg?width=240&version=7069B5DD0A6388986A1C1344C308ACA7&format=webp",
        "date": "24 nov 2023",
        "genre": "Anime",
        "description": "Tokyo, i slutet av andra världskriget. 11-årige Mahito har förlorat sin mor i en brand och har svårt att acceptera att hans far har gift om sig med mammans yngre syster, Nahuto. På gården där de bor finns ett isolerat torn. När Nahuto plötsligt försvinner letar Mahito i tornet och hamnar plötsligt i en annan värld. Ett mystiskt rike där de levande och döda går sida vid sida.", 
    },
    {
        "id": 7,
        "title": "Trolls 3",
        "image": "https://catalog.cinema-api.com/cf/images/ncg-images/7bc0a9a4e693437eb25d6fb514915a12.jpg?width=240&version=AF970D2DF41BEAA3034FC524D8E2F260&format=webp",
        "date": "13 okt 2023",
        "genre": "Animerat,Äventyr,Komedi,Familj",
        "description": "Efter en tid med sann vänskap och obevekligt flirtande är nu Poppy och Kvist äntligen ett officiellt par. När de kommer varandra närmare, upptäcker Poppy att Kvist har ett hemligt förflutet. Han var en gång med i hennes favoritpojkband, fenomenet BroZone, tillsammans med sina fyra bröder: Floyd, John Dory, Spruce och Clay. BroZone upplöstes när Kvist fortfarande var jätteliten, och även familjen splittrades. Kvist har inte sett sina bröder sedan dess. Men när Kvists bror Floyd kidnappas, för sina musikaliska talanger, av ett par skurkaktiga popstjärnor, Velvet och Veneer, ger sig Kvist och Poppy ut på en spännande och känslomässig resa för att återförena de andra bröderna och rädda Floyd från ett ännu värre öde än att bli en bortglömd popstjärna.", 
    },
    {
        "id": 8,
        "title": "Nelly Rapp - Dödens spegel",
        "image": "https://catalog.cinema-api.com/cf/images/ncg-images/6083f8d0476f4954b062ef35ee46ed07.jpg?width=240&version=435B119DAF6846384CBC7510C8D1AE40&format=webp",
        "date": "20 okt 2023",
        "genre": "Familj,Äventyr,Komedi",
        "description": "Nelly och hunden London får sällskap av Valle då de beger sig ut i Svartskogen för att finna Dödens spegel. En resa som tar dem allt djupare in i skogen och till den plats där Nellys mamma en gång försvann.", 
    },
    {
        "id": 9,
        "title": "Journey to Bethlehem",
        "image": "https://catalog.cinema-api.com/cf/images/ncg-images/e6020bb8d85a416799d772161e2ceda3.jpg?width=240&version=149C7FE99FA9D076F9EED8C59DD95599&format=webp",
        "date": "1 dec 2023",
        "genre": "Musikal,Äventyr,Familj",
        "description": "En ung kvinna som bär på ett otroligt ansvar. En ung man sliten mellan kärlek och heder. En svartsjuk kung som är beredd att göra allt för att behålla sin krona. Detta musikaliska juläventyr för hela familjen väver samman klassiska julmelodier med humor, tro och nya poplåtar för att berätta den största historien någonsin den om Maria och Josef och Jesu födelse.", 
    },
    {
        "id": 10,
        "title": "Five Nights at Freddy's",
        "image": "https://catalog.cinema-api.com/cf/images/ncg-images/ef1a1fa65c7d46e49bf31140cebf6bb7.jpg?width=240&version=10EED1DAA4D92B4D5F94FF5A417DC28C&format=webp",
        "date": "27 okt 2023",
        "genre": "Skräck",
        "description": "En säkerhetsvakt börjar jobba på Freddy Fazbear's Pizza. När han tillbringar sin första natt på jobbet, inser han att nattskiftet på Freddy's inte kommer att bli så lätt att ta sig igenom. Det skrämmande skräckspelsfenomenet blir en blodisande filmhändelse när Blumhouse bolaget som producerat M3GAN, The Black Phone och The Invisible Man tar Five Nights at Freddy's till bioduken.",
    },
    {
        "id": 11,
        "title": "Silent Night",
        "image": "https://catalog.cinema-api.com/cf/images/ncg-images/e8f415689a004b0c83a27168d5ad7474.jpg?width=240&version=D01C7D0767C734AED1612E3C58AFB465&format=webp",
        "date": "8 dec 2023",
        "genre": "Action",
        "description": "En pappa bevittnar hur hans lille son dör när han hamnar mitt i korselden vid en gänguppgörelse. Han gör hämnden till sin livsuppgift och gör allt för att hämnas de som dödade hans son.", 
    },
    {
        "id": 12,
        "title": "Avgrunden",
        "image": "https://catalog.cinema-api.com/cf/images/ncg-images/5d3cb9d45ca841d8859bf76e7d736345.jpg?width=240&version=2669451910E42C1BB6C7201C92506CCC&format=webp",
        "date": "15 sep 2023",
        "genre": "Hela Kiruna kommer troligen rasa, frågan är inte om utan när. När ett gruvras inträffar i Kiirunavaragruvan börjar en kapplöpning mot klockan. Säkerhetschefen Frigga (Tuva Novotny) är fast i gruvan och måste ta sig upp för att varna staden och rädda sin familj innan katastrofen är ett faktum.",
        "description": "15 sep 2023", 
    },
];
